<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PAY_ID_CARD</name>
   <tag></tag>
   <elementGuidId>b756c6fd-181c-463a-83eb-5b74335ebb7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/form/div[3]/div[1]/div[5]/div[1]/table/tbody/tr/td[1]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
