<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ACTIONS_BUTTON</name>
   <tag></tag>
   <elementGuidId>6845e095-2ab5-4c21-933f-0585c752f535</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content-wrapper&quot;]/div/div/div[2]/div/div/div/div[1]/div[1]/div[1]/div[1]/table/tbody/tr[1]/td[2]/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
