<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CONV_FEE</name>
   <tag></tag>
   <elementGuidId>388a5ee1-25a2-47cc-8261-7a3a37b37e67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content-wrapper&quot;]/div/div/div[2]/div/div/div/div[1]/div[1]/div[1]/div[1]/table/tbody/tr[5]/td[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
